
sudo: required

services:
  - docker

before_install:
  - docker build -t latest .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push andigitalsophie/learning-ci;
    fi
